[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --prefer-offline"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  NETLIFY_USE_YARN = "true"

[build.resources]
  memory = 4096
