module.exports = [
  {
    name: "React",
    hebrewName: "ריאקט",
    officialSite: "he.reactjs.org",
    videoTutorials: [
      { url: "sBws8MSXN7A" },
      { url: "Ke90Tje7VS0" },
      { url: "xsSnOQynTHs" },
      { url: "3frXLe5woQ8" },
      { url: "1iAG6h9ff5s" },
      { url: "nusgoj74a3Y" },
      { url: "sYhMEo6eoe" },
      { url: "114SMzf0vjA" },
      { url: "sYhMEo6eoeQ" },
      { url: "k3dbO82WuOg" },
      { url: "amn5sVd2k6U" },
      { url: "ovzI_8501sg" },
      { url: "VylTNsFy3tc" },
      { url: "2DkLGLH3J1I" },
      { url: "_D1JGNidMr4" },
      { url: "ZBxMljq9GSE" }
    ],
    color: "#5adafd"
  },
  {
    name: "Vue",
    hebrewName: "ויו",
    officialSite: "vuejs.org",
    videoTutorials: [
      { url: "Wy9q22isx3U" },
      { url: "78tNYZUS-ps" },
      { url: "utJGnK9D_UQ" },
      { url: "JLc-hWsPTUY" },
      { url: "W_ajgnqjK_g" },
      { url: "dFTsbSRJuIw" },
      { url: "VugasBUoBdI" },
      { url: "rt2gNWjydAM" },
      { url: "lzhnOgwto0M" },
      { url: "EsSi4cER48E" },
      { url: "DZyWNS4fVE0" },
      { url: "mS9-fTrgjrA" },
      { url: "REqu-nKek-o" },
      { url: "VqnJwh6E9ak" },
      { url: "ISVaMijczKc" },
      { url: "6-us2D7GQCk" },
      { url: "ko5Eijiaozo" },
      { url: "5pvG6fzkdFM" }
    ],
    color: "#41b883"
  },
  {
    name: "Angular",
    officialSite: "angular.io",
    hebrewName: "אנגולר",
    videoTutorials: [
      { url: "GWws2gi9JEM", hebrew: true },
      { url: "9P5DTlg9oLc" },
      { url: "DBjPIabiRNg" },
      { url: "gCcl2MSzB7I" },
      { url: "bo1Wu0aiigU" },
      { url: "lApggVS0icc" },
      { url: "1hyjLD7pk10" },
      { url: "fXHyqSIIF9Q" },
      { url: "eOZ7n-5uASo" },
      { url: "IqpjIQ0pfkA" },
      { url: "Ob7KZnZFZRk" },
      { url: "FQ__z26TsHU" },
      { url: "3lKVCFBW5So" },
      { url: "-WEI7ilKvc4" },
      { url: "Ous6v0r7kXc" },
      { url: "TQ-0stE4Y0o" },
      { url: "1iW0KnEk6UM" },
      { url: "WWQZCDegWHg" },
      { url: "hPaY3DHJnbo" },
      { url: "-zW1zHqsdyc" },
      { url: "nZbZ5AHZJnc" },
      { url: "MKApWSDJeiw" },
      { url: "jYvkMv7LzCw" },
      { url: "HB6ftmxKzL8" },
      { url: "vrdHEBkGAow" },
      { url: "k5E2AVpwsko" },
      { url: "YxyeX8-9lb0" }
    ],
    color: "#c5002a"
  },
  {
    name: "Python",
    hebrewName: "פייתון",
    officialSite: "python.org",
    videoTutorials: [
      { url: "-wikR15AYWY" },
      { url: "1Xa_iDqvg94" },
      { url: "A1HUzrvS-Pw" },
      { url: "qmWCT_OgrKQ" },
      { url: "ukxMIsNeqU" },
      { url: "1AGyBuVCTeE" }
    ],
    color: "#ffd530"
  },
  {
    name: "HTML",
    hebrewName: "HTML",
    officialSite: "http://www.ecmascript.org/",
    videoTutorials: [
      { url: "88PXJAA6szs" },
      { url: "b-lny3-7Lo" },
      { url: "cw5f_P3pZs" },
      { url: "dkP1rDqUll8" },
      { url: "tZN6o0ylao" },
      { url: "Z55B-PN5Ys0" },
      { url: "qOAdCdW6gg" },
      { url: "5h-YgYXdnSQ" },
      { url: "0FYFvvX2-A4" }
    ],
    color: "#e65c18"
  },
  {
    name: "CSS",
    hebrewName: "CSS",
    officialSite: "https://www.w3.org/css/",
    videoTutorials: [
      { url: "J35jug1uHzE" },
      { url: "ieTHC78giGQ" },
      { url: "wNX7lWzchow" }
    ],
    color: "#1673b6"
  },
  {
    name: "JavaScript",
    hebrewName: "ג'אווהסקריפט",
    officialSite: "https://www.w3.org/javascript/",
    videoTutorials: [
      { url: "10ujZygJzMQ" },
      { url: "wik23D_gyCo" },
      { url: "H63dVFDuJDM" },
      { url: "Udae53g40ak" },
      { url: "lzSTgchmFoU" },
      { url: "HMjU2_-DWLw" },
      { url: "gsfbh17Ax9I" },
      { url: "Wr4fhvQians" },
      { url: "tsuhoLiSWmU" },
      { url: "bHOmtpYo6zE" },
      { url: "95v9d4qOKqM" },
      { url: "ItYye9h_RXg" },
      { url: "W6NZfCO5SIk" },
      { url: "EhpmNyR2Za0" },
      { url: "fju9ii8YsGs" }
    ],
    color: "#c2b134"
  },
  {
    name: "Git",
    hebrewName: "גיט",
    officialSite: "https://git-scm.com/",
    videoTutorials: [
      { url: "SWYqp7iY_Tc" },
      { url: "Mi7LDN4cvq8" },
      { url: "5iBZiEJiM_U" },
      { url: "2RoXCEVWUN4" },
      { url: "ep5JBalCD_g" },
      { url: "nrV0wVvI3-4" }
    ],
    color: "#f44f29"
  },
  {
    name: "WordPress",
    hebrewName: "וורדפרס",
    officialSite: "https://wordpress.org/",
    videoTutorials: [
      { url: "0zwDo5hH2LQ" },
      { url: "NmBADqf1UY0" },
      { url: "AYua5KpkBCg" },
      { url: "4teO1oHuQbA" },
      { url: "kzxzbRF6alg" },
      { url: "4lbKadpMn4U" },
      { url: "OBHPqgiN6lk" },
      { url: "3uYHcetEy40" },
      { url: "PiqeNvGklSM" },
      { url: "ZCxPIhdB6Ek" },
      { url: "3DtQbVfC6cE" },
      { url: "7-agKKX9TPo" },
      { url: "Wv_QYADAm9w" },
      { url: "Y64r8eGaS0Q" },
      { url: "Wq6gAj0i_P8" },
      { url: "WIoFEbGAiEw" },
      { url: "xLN4LqdkR4c" },
      { url: "z4ULR6t3MIE" },
      { url: "BZSSLQjVf1U" },
      { url: "dO6QdlFBozw" },
      { url: "3_TAJGaW1J8" },
      { url: "cLBc8S21rRM" },
      { url: "SUOATIrsqwM" },
      { url: "Pp_NuiCJFhs" },
      { url: "i-OFd0oE9BU" },
      { url: "tJ0kzKaUHKs" }
    ],
    color: "#494949"
  },
  {
    name: "Elementor",
    hebrewName: "אלמנטור",
    officialSite: "https://elementor.com/",
    videoTutorials: [
      { url: "N1W9kumpF64" },
      { url: "Kq4hsUnzrlI" },
      { url: "n8Vp8OOoPl8" },
      { url: "MwCw-xIVSl0" },
      { url: "7Mz1rmljtOk" },
      { url: "XcWLNqEZnXI" },
      { url: "6H7nXlshkm0" },
      { url: "KgmjkGNJvUY" },
      { url: "mdphDST-ZtM" },
      { url: "n8zA70d6-KU" },
      { url: "B5NS5NNoI9E" },
      { url: "neRuPTBAV8w" },
      { url: "IMfosDIBhe4" },
      { url: "H-Y0vdkU0dc" },
      { url: "tBd9ZifIYFA" },
      { url: "EPvf9ZfDAsg" },
      { url: "XEtv6e7_-Io" },
      { url: "fdZ5lt7OQpU" },
      { url: "BGc-B9E2xso" },
      { url: "WaXDixTrOCo" },
      { url: "MV0KId5JhLk" },
      { url: "spOpSzNEpoI" },
      { url: "q_MWcY5Nu8k" },
      { url: "xQ6ecbNI6NM" }
    ],
    color: "#8d2d6b"
  },

  {
    name: "PHP",
    hebrewName: "PHP",
    officialSite: "https://www.php.net/",
    videoTutorials: [
      { url: "ZdP0KM49IVk" },
      { url: "y_gQ0dMJ0hU" },
      { url: "ZA0malVnbbE" },
      { url: "AKsf77W1ytA" },
      { url: "cuBNeIWbnAw" }
    ],
    color: "#6181B6"
  },

  {
    name: "NodeJS",
    hebrewName: "JS נוד",
    officialSite: "https://nodejs.org/en/",
    videoTutorials: [
      { url: "AA2G9ZFIN8o" },
      { url: "KujWrArivjo" },
      { url: "sqf_2EIRdpk" },
      { url: "3Dzt8FL2OxI" },
      { url: "UTE6kQXVa-M" },
      { url: "OIGb6W9T4AY" },
      { url: "yZ8-vEusBwg" },
      { url: "GK-tFvpIR7c" },
      { url: "djt-IRn8LvU" },
      { url: "vCXlp7E5Mzk" },
      { url: "UrUirVYByGI" },
      { url: "Z1ktxiqyiLA" },
      { url: "DZ_bRk8JWDM" },
      { url: "DNPVqK_woRQ" },
      { url: "9neEE_HowzM" }
    ],
    color: "#83CD29"
  }
];
